/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Drfreshdr (https://sketchfab.com/Drfreshdr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shopping-cart-fc5e2e7f0c8a4e0eb208bfcc7aa130e0
Title: Shopping Cart
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export  default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.24, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_Material001_0_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Torus_Material003_0.geometry} material={materials['Material.003']} position={[1.1, 0.78, -1]} rotation={[0, Math.PI / 2, 0]} scale={0.8} />
        <mesh geometry={nodes.Cylinder_Material_0.geometry} material={materials.Material} position={[0, 2.1, 1.5]} rotation={[0, Math.PI / 2, 0]} scale={[0.07, 0.07, 0.9]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
